version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: tvsCatalog-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 472180
      MYSQL_DATABASE: tvsCatalogDB
    ports:
       - "3386:3386"
    cap_add:
        - SYS_NICE