version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: tvCatalog-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Ac160301*
      MYSQL_DATABASE: tvCatalogDB
    ports:
    - "3306:3306"
    cap_add:
      - SYS_NICE
